### ISSUE TITLE
Arc/Circle  entities do not have a start_point

### ISSUE THREAD

**Issue by wamiq-reyaz** [PrincetonLIPS/SketchGraphs#10]
https://github.com/PrincetonLIPS/SketchGraphs/blob/e69dd49272e2fc35b3ec34c8b9109268ad29878f/sketchgraphs/data/constraint_checks.py#L257

Hey,
.
I was trying to work through your code and this strikes me as a bug. 
The entities Arc/Circle would be concentric if they have the same center. You test for the center and the start point being the same.
I don't think the Circle even has a start_point. Does this sound right?

**Comment by ariseff** [comment]
Thanks for the catch. This was introduced during some prerelease refactoring.
Fixed.
