### ISSUE TITLE
how to get "distinct" shapes?

### ISSUE THREAD

**Issue by evanthebouncy** [PrincetonLIPS/SketchGraphs#11]
pardon my vagueness as I don't know how to properly articulate this yet, but try to reach me half-way.

I'm using your dataset for a kind of cognitive experiment, i.e. just want a sample of cool shapes that looked different.

I downloaded the validation set, which contained more than enough interesting shapes. however, noticed that most of the shapes in validation are duplicates in that they're conceptually same, i.e. a single circle, albeit of different sizes, a single rectangle, albeit different width/heights, or a combination of.

what would you suggest to get a set of "interesting" shapes? I thought about doing stuff like generating a kind of "fingerprint" for each shape, such as the number of lines and such, and keeping one shape per fingerprint. however it does seem a bit restrictive. I just want some idea that I can play with.  

the "gold standard" would be using the constraint solver and see if some shapes can be isomorphic to others by modifying the parameters while still satisfying the constraints. but no way I'm doing that lol. something quick and dirty would be preferable.

thanks in advance

**Comment by ariseff** [comment]
Awesome use case!

To start, try simply filtering by number of primitives (the length of `entities`). In the provided validation set, there are 120K sketches with >= 5 primitives and 86K with >= 6. These correspond to about 1/3 and 1/4 of the validation dataset, respectively, and tend to display much more visual variety.

**Comment by evanthebouncy** [comment]
@ariseff ah thanks that's a good solution! here's a follow up question : how would we automatically extract some human intuitive features that would allow someone to describe a shape? for instance for each shape I want to generate, automatically, a bit-vector where each bit correspond to a feature such as "symmetric" or "contain 5 rectangles". 

I understand some of these features might be more easy or difficult to extract automatically from the sketch datastructure, but what are something that you have in mind which is both easy to imiplement and fairly intuitive for human to use and fairly descriptive in distinguishing these shapes from one another? It doesn't need to be perfect, and I'm sure you have some ideas.

my biggest question is really, something such as "rectangle" or "circle" might not be explicitly represented, as the sketch is made out of line segments and constraints that implicitly form a rectangle. so any ideas would be great.

again, thanks in advance

**Comment by ariseff** [comment]
Interesting! One thing to emphasize is that the primitives in the dataset are generally in their solved states. We extract their final positions from Onshape after the constraint solving step has already taken place. So depending on the complexity of your features of interest, you may be able to use some rule-based strategies to detect them, e.g., a simple function to verify if 4 given line segments form a rectangle. For higher-level features, this may become difficult without learning.

**Comment by ariseff** [comment]
(offline discussion)
