### ISSUE TITLE
KeyError: xCenter in sketchgraphs/pipeline/graph_model/quantization.py  

### ISSUE THREAD

**Issue by JoeLambourne** [PrincetonLIPS/SketchGraphs#12]
Hello SketchGraph Team,

I have been trying to look at the output of your generative model and hit a problem.  I'm not sure if perhaps I did something wrong at the training or sampling stage.  

I tried the generative model as follows

```
python -m sketchgraphs_models.graph.train --dataset_train /path/to/data/sg_t16_train.npy
```

This generated the following files
```
0219/time_104135
0219/time_104135/args.txt
0219/time_104135/model_state_20.pt
0219/time_104135/model_state_40.pt
0219/time_104135/model_state_30.pt
0219/time_104135/model_state_10.pt
0219/time_104135/eval
0219/time_104135/eval/events.out.tfevents.1613731298.lamboujdevbox.10253.1
0219/time_104135/model_state_50.pt
0219/time_104135/events.out.tfevents.1613731298.lamboujdevbox.10253.0
```

I then try to run the `sketchgraphs_models/graph/sample.py` to extract some generated examples from the model.  I did this using
```
python -m sketchgraphs_models.graph.sample --output_path /path/to/output/sampled_data.pkl --model_state path/to/output/0219/time_104135/model_state_50.pt
```

I hit an error

```
Exception has occurred: KeyError
'xCenter'
  File "xxxx/sketchgraphs/pipeline/graph_model/quantization.py", line 258, in _numerical_features
    feature[i + offset] = int(np.searchsorted(edges, params[param_name]))
 
````

Digging into what is going on I see the dictionary `params` is generated by the following code

[sketchgraphs/pipeline/graph_model/quantization.py#L314-L315](https://github.com/PrincetonLIPS/SketchGraphs/blob/master/sketchgraphs/pipeline/graph_model/quantization.py#L314-L315)
```
        for i, (param_name, centers) in enumerate(self._bin_centers.get(target, {}).items()):
            features[param_name] = centers[index[i + offset]]
```

Here `target`has type `<TargetType.NodeCircle: 8>` but inside the `self._bin_centers` dictionary we have `<EntityType.Circle: 2>`.   Hence the `features` dictionary isn't built up correctly.

I find that adding the code 

```
        _entity_label_from_target_type_dict = {
            TargetType.NodeArc: datalib.EntityType.Arc,
            TargetType.NodeCircle: datalib.EntityType.Circle,
            TargetType.NodeLine: datalib.EntityType.Line,
            TargetType.NodePoint: datalib.EntityType.Point
        }

        target_entity = _entity_label_from_target_type_dict[target]

        for i, (param_name, centers) in enumerate(self._bin_centers.get(target_entity, {}).items()):
            features[param_name] = centers[index[i + offset]]
````
fixed the problem.

Could you let me know if I did something wrong at the training or test phase.  If this fix would be useful for you I can create a PR to submit it back to the main repo.

Thank you for your help.

**Comment by wendazhou** [comment]
Hi, thanks a lot for your very detailed report!

This definitely appears to be a bug in our code, a PR to fix that would be welcome! If you end up doing so, it would be great to create the `_entity_label_from_target_type_dict` dictionary right below [`_entity_label_to_target_type_dict`](https://github.com/PrincetonLIPS/SketchGraphs/blob/183c65f82d71d82c62b253092e9b7fa65846a3e6/sketchgraphs/pipeline/graph_model/quantization.py#L204), and do so programatically, i.e.:
```{python}
_entity_label_from_target_type_dict = {v: k for k, v in _entity_label_to_target_type_dict.items()}
```
