### ISSUE TITLE
External Node and constraints on the external

### ISSUE THREAD

**Issue by wamiq-reyaz** [PrincetonLIPS/SketchGraphs#13]
Hey there,

I am trying to parse the dataset. I don't completely grok the external node. Moreso the fact that there are certain points that are _coincident_ to it.

What is it used for? Is it expected by the OnShape API? What would happen if one submits a sequence to OnShape without a) the external node b) constraints on the external node? I am guessing the constraints are mostly coincidences.

Thanks!

**Comment by ariseff** [comment]
The external node represents any default geometry outside of the user-defined primitives in a sketch, e.g., the origin or the x or y-axis of the sketch plane. A limitation of Onshape's API is that while constraints involving external geometry are retrievable, the _specific_ external entity involved is not.

See https://forum.onshape.com/discussion/12923/api-resolving-external-entities and footnote 2 of our paper.

With that being said, one can often partially disambiguate the external entity involved in a particular constraint. For example, if a line endpoint is constrained to be coincident with the external node, and the line endpoint has coordinates [x=5, y=0], we can reasonably guess that the x-axis is the relevant external entity.

It is not expected by the Onshape API. Actually, a corollary of the above limitation is that there is no way, currently, to apply a constraint referencing external geometry via the API.

I hope that helps!
