### ISSUE TITLE
NaNs in sketchgraphs_models/nn/summary.py cohen_kappa() when training on a subset of sg_t16_train.npy

### ISSUE THREAD

**Issue by JoeLambourne** [PrincetonLIPS/SketchGraphs#14]
Hi SketchGraphs experts,

I'm trying to train on a subset of the dataset sg_t16_train.npy with some "geometric" duplicates removed.  It was a very trivial change to  the `GraphDataset` from `sketchgraphs_models/graph/dataset/__init__.py` to get the data loader to choose only sequences from my de-duplicated list.

When training on the subset I find that I get some NaNs reported in the kappa edge statistics 

```
Kappa Edges
EdgeAngle: aligned (nan); clockwise (nan); angle (nan)
EdgeLength: direction (1.000); length (-0.043)
EdgeDistance: direction (0.000); halfSpace0 (0.019); halfSpace1 (0.371); length (0.000)
EdgeDiameter: length (-0.013)
EdgeRadius: length (0.033)
```

Debugging I see that the NaNs get generated in the `cohen_kappa()` function in `sketchgraphs_models/nn/summary.py`

For the `EdgeAngle` TargetType the value of `self.recorded = [0, 0, 0, 0]`.  

```
        pm = self.prediction_matrix.float()
        N = self.recorded.sum().float()    <------ N == 0 

        p_observed = pm.diag().sum() / N                                                          <---- NaNs in here
        p_expected = torch.dot(pm.sum(dim=0), pm.sum(dim=1)) / (N * N)     <---- and here
```

My understanding of the problem is that the data subset doesn't contain any  `EdgeAngle` constraints and consequently I can fix this with 

```
        if N == 0:
            return 1
```

Does this sound like a valid solution, or are there other parts of the code I would need to change to work with a subset of the data?

Thank you for your help with this!

**Comment by wendazhou** [comment]
Hi Joe,

this should be a perfectly fine solution for dealing with your use case, as the metrics in `summary` are for display only and don't affect the model in any way. You could also consider using [`torch.nan_to_num`](https://pytorch.org/docs/stable/generated/torch.nan_to_num.html) if you have pytorch 1.8

**Comment by JoeLambourne** [comment]
Thanks Wenda,

So currently I just check for `N==0` and return like this

```
        if N == 0:
            return 1
```

I can submit a PR with just this change if you think it might be useful.
