### ISSUE TITLE
onshape.request() now returning status_code:500 An internal error has occurred

### ISSUE THREAD

**Issue by JoeLambourne** [PrincetonLIPS/SketchGraphs#15]
Is anybody else experiencing issues making OnShape calls?  I'm currently getting

```
status_code:500
An internal error has occurred; support code xxxxx
```

I was previously able to make OnShape calls with the same code.  Has there been a change to the FeatureScript microversion?

**Comment by ariseff** [comment]
Occasionally the FeatureScript template version will become out-of-date with your document. Try running the command found at the bottom of [this page](https://princetonlips.github.io/SketchGraphs/onshape_setup).

**Comment by JoeLambourne** [comment]
Thank you @ariseff !   Yes.  That worked.
