### ISSUE TITLE
Explanation of some schemata

### ISSUE THREAD

**Issue by wamiq-reyaz** [PrincetonLIPS/SketchGraphs#19]
I don't quite understand some schemata - eg the `Horizontal` the `Horizontal` constraint with just one reference to `local0` makes sense but in what context would a `Horizontal` constraint that refers to `local0, local1` make sense?

Not quite sure I get that.

**Comment by ariseff** [comment]
A horizontal constraint acting on two points simply requires them to have the same y coordinate. See this example where I've added a horizontal constraint between a line endpoint and the center of a circle:

https://user-images.githubusercontent.com/13666501/118050184-d194ac00-b34c-11eb-8a32-c7fd33edb407.mp4
