### ISSUE TITLE
Cannot run `pip install -r requirements.txt`

### ISSUE THREAD

**Issue by lxuechen** [PrincetonLIPS/SketchGraphs#5]
Hi, thanks for the amazing working!

This is a really minor issue, but it would be nice if we'd be able to install the requirements via 
`pip install -r requirements.txt`

This currently breaks due to `pytorch>=1.5` and `python>=3.7`.

**Comment by lxuechen** [comment]
Just realized `requirements.txt` is set to a format that works well with `conda install ...`. Feel free to close this issue if that's the encouraged behavior.

**Comment by wendazhou** [comment]
Yes, we recommend installing with conda as it handles binary dependencies better (for example, the cuda version with pytorch). I will add something in the documentation to this effect. Thanks for the feedback!
