### ISSUE TITLE
`Bus error (core dumped)` after attempting to run the model example

### ISSUE THREAD

**Issue by lxuechen** [PrincetonLIPS/SketchGraphs#6]
To provide a bit more context, I cloned a fresh repo and downloaded the data as well as the metadata. I ran 
```shell script
python -m sketchgraphs_models.graph.train --dataset_train sg_t16_train.npy
```
This produced a bus error. 

The caveat is that I did not install the python package via `pip install .` or `python setup.py install`, as I'm currently still trying to figure out some issues associated with nvcc. I did install all the relevant packages in `requirements.txt`. Is this an expected consequence of not installing the cuda extension?

**Comment by lxuechen** [comment]
Just upgraded my `nvcc` and successfully installed the package. Still geting the bus error.

**Comment by lxuechen** [comment]
Ok, I did a manual binary search and found [the line](https://github.com/PrincetonLIPS/SketchGraphs/blob/e612f594b66e9e0ab0ba1638dd748a21b13720d0/sketchgraphs/data/flat_array.py#L319
) that's causing the problem.

**Comment by wendazhou** [comment]
Thanks for taking such a close look! We currently load all the dataset into memory for efficiency reasons - how much memory do you have on your machine?

**Comment by lxuechen** [comment]
So correct me if I'm wrong, but I don't think the problem is that I don't have enough memory. It's rather that I don't have enough *shared memory* enabled on my machine. Looking closer at the data, I see that there's a `np.memmap` object which originally prevents a out of RAM issue, but that object is thereafter copied(?) and placed in shared memory. 

Is there a particular reason to using `shared_memory_()`, as opposed to just converting the memmap to a numpy.ndarray and then to torch Tensors? Is there some type of multipleprocessing happnening deep in the code?
